import { z } from '$lib/ai';
import type { Resource } from '$lib/schema/resource';
import type { LLMChatMessage } from '$lib/server/types';
import {
	requestLLM,
	checkSubtaskCompleted
	// cleanForeignLanguage is handled by _processLLMResponse within requestLLM
} from './gemini_utils';
import {
	DOCS_CONTEXT_RESPONSE_PROMPT,
	DOCS_CONTEXT_SYSTEM_PROMPT,
	HEY_HELP_PROMPT,
	INTRODUCTION_PROMPT,
	SUBTASK_PREFIX_PROMPT
} from './prompt';
import { isHarmfulContent, isOffTopic } from './gemini_moderation';

/**
 * Generates an introductory message for a given task, subtasks, and resources.
 * The message is generated by the LLM based on a predefined prompt.
 *
 * @param task The main task description.
 * @param subtasks A list of subtasks.
 * @param resources An array of resources (documents) relevant to the task.
 * @returns An object containing the success status, the generated introductory response, or an error message.
 */
export async function generateIntroduction(
	task: string,
	subtasks: string[],
	resources: Resource[]
) {
	// Format resources and subtasks for inclusion in the system prompt.
	const formatted_docs = resources
		.map((doc, index) => {
			const title = doc.name || `Document ${index + 1}`;
			return `[${title}]:\n${doc.content}`;
		})
		.join('\n\n');

	const formattedSubtasks = subtasks.map((subtask) => {
		return SUBTASK_PREFIX_PROMPT.replace('{subtask}', subtask);
	});

	// Construct the system prompt using templates and provided data.
	const system_prompt = DOCS_CONTEXT_SYSTEM_PROMPT.replace('{task}', task)
		.replace('{subtasks}', formattedSubtasks.join('\n'))
		.replace('{resources}', formatted_docs)
		.replace('{response_prompt}', ''); // No specific response prompt for introduction

	// Define the expected schema for the LLM's response.
	const schema = z.object({
		introduction: z.string() // Expects a single string for the introduction.
	});

	try {
		// Call the LLM using the requestLLM utility.
		// Text processing (normalization, language cleaning) is handled by requestLLM.
		const response = await requestLLM(
			system_prompt,
			[{ role: 'user', content: INTRODUCTION_PROMPT }], // Initial user message to trigger introduction
			schema,
			0.5 // Temperature setting for generation
		);

		if (!response.success || !response.result) {
			// Handle cases where LLM call fails or returns no result
			throw new Error(response.error || 'Failed to generate introduction due to LLM error.');
		}

		return {
			success: true,
			response: response.result.introduction, // The introduction text, already processed
			error: ''
		};
	} catch (error) {
		console.error('Error in generateIntroduction for task:', task, error);
		return {
			success: false,
			response: '',
			error: error instanceof Error ? error.message : 'Error in generateIntroduction'
		};
	}
}

/**
 * Handles a chat interaction with the LLM based on provided documents (resources).
 * It incorporates task context, subtask status, chat history, and performs moderation checks.
 *
 * @param history Current chat history.
 * @param task The main task description.
 * @param subtasks A list of subtasks.
 * @param subtaskCompleted Boolean array indicating completion status of each subtask.
 * @param resources An array of resources relevant to the task.
 * @returns An object containing success status, LLM response, subtask completion updates, moderation warnings, or an error message.
 */
export async function chatWithLLMByDocs(
	history: LLMChatMessage[],
	task: string,
	subtasks: string[],
	subtaskCompleted: boolean[],
	resources: Resource[]
) {
	// Format resources and subtasks for the system prompt.
	const formatted_docs = resources
		.map((doc, index) => {
			const title = doc.name || `Document ${index + 1}`;
			return `[${title}]:\n${doc.content}`;
		})
		.join('\n\n');

	const formattedSubtasks = subtasks.map((subtask, index) => {
		// Indicate completion status in the prompt.
		return subtaskCompleted[index]
			? `(完成)` // Chinese for "Completed"
			: `(未完成)` + SUBTASK_PREFIX_PROMPT.replace('{subtask}', subtask); // Chinese for "Not Completed"
	});

	// Construct the system prompt.
	const system_prompt = DOCS_CONTEXT_SYSTEM_PROMPT.replace('{task}', task)
		.replace('{subtasks}', formattedSubtasks.join('\n'))
		.replace('{resources}', formatted_docs)
		.replace('{response_prompt}', DOCS_CONTEXT_RESPONSE_PROMPT); // Specific response instructions

	// Define the expected schema for the LLM's chat response.
	const schema = z.object({
		affirmation: z.string(),
		elaboration: z.string(),
		question: z.string()
	});

	try {
		// Perform several operations in parallel:
		// 1. Get the main LLM chat response.
		// 2. Check for subtask completion based on the latest history.
		// 3. Check the latest user message for harmful content.
		// 4. Check if the latest user message is off-topic.
		const [llmResponse, subtask_check, moderation, off_topic_check] = await Promise.all([
			requestLLM(system_prompt, history, schema, 0.5), // Main LLM call
			checkSubtaskCompleted(history, subtasks), // Utility from gemini_utils
			isHarmfulContent(history.length > 0 ? history[history.length - 1].content : ''), // Moderation check
			isOffTopic(history, task, subtasks) // Moderation check
		]);

		// Aggregate results and handle potential errors from any parallel operation.
		if (
			!llmResponse.success ||
			!subtask_check.success ||
			!moderation.success ||
			!off_topic_check.success
		) {
			const errors = [
				llmResponse.error,
				subtask_check.error,
				moderation.error,
				off_topic_check.error
			]
				.filter(Boolean) // Filter out empty error messages
				.join('; ');
			throw new Error(`One or more sub-operations failed: ${errors || 'Unknown error'}`);
		}

		if (!llmResponse.result) {
			// Should be caught by llmResponse.success check, but as a safeguard:
			throw new Error('LLM response result is null for chatWithLLMByDocs');
		}

		// Destructure the already processed (normalized, language-cleaned) LLM response parts.
		const { affirmation, elaboration, question } = llmResponse.result;
		const combined_response = `${affirmation}\n\n${elaboration}\n\n${question}`;

		return {
			success: true,
			response: combined_response,
			subtask_completed: subtask_check.completed || [], // Default to empty array if undefined
			warning: {
				moderation: moderation.harmfulContent || false, // Default to false
				off_topic: off_topic_check.offTopic || false // Default to false
			},
			error: ''
		};
	} catch (error) {
		console.error('Error in chatWithLLMByDocs for task:', task, error);
		return {
			success: false,
			response: '',
			subtask_completed: [],
			warning: {
				moderation: false,
				off_topic: false
			},
			error: error instanceof Error ? error.message : 'Error in chatWithLLMByDocs'
		};
	}
}

/**
 * Generates a help message from the LLM when summoned (e.g., "Hey Help").
 * Similar to `chatWithLLMByDocs` but uses a specific prompt for help requests.
 *
 * @param history Current chat history.
 * @param task The main task description.
 * @param subtasks A list of subtasks.
 * @param resources An array of resources relevant to the task.
 * @returns An object containing success status, the LLM's help response, or an error message.
 */
export async function getHeyHelpMessage(
	history: LLMChatMessage[],
	task: string,
	subtasks: string[],
	resources: Resource[]
) {
	// Format resources and subtasks for the system prompt.
	const formatted_docs = resources
		.map((doc, index) => {
			const title = doc.name || `Document ${index + 1}`;
			return `[${title}]:\n${doc.content}`;
		})
		.join('\n\n');

	const formattedSubtasks = subtasks.map((subtask) => {
		return SUBTASK_PREFIX_PROMPT.replace('{subtask}', subtask);
	});

	const system_prompt =
		DOCS_CONTEXT_SYSTEM_PROMPT.replace('{task}', task)
			.replace('{subtasks}', formattedSubtasks.join('\n'))
			.replace('{resources}', formatted_docs) + HEY_HELP_PROMPT;

	const schema = z.object({
		affirmation: z.string(),
		elaboration: z.string(),
		question: z.string()
	});

	try {
		const response = await requestLLM(system_prompt, history, schema, 0.5); // Text will be processed

		if (!response.success || !response.result) {
			throw new Error(response.error || 'Failed to get HeyHelp message');
		}

		const { affirmation, elaboration, question } = response.result; // Already processed
		const combined_response = `${affirmation}\n\n${elaboration}\n\n${question}`;

		return {
			success: true,
			response: combined_response,
			error: ''
		};
	} catch (error) {
		console.error('Error in getHeyHelpMessage:', error);
		return {
			success: false,
			response: '',
			error: error instanceof Error ? error.message : 'Error in getHeyHelpMessage'
		};
	}
}
